# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'
require 'net/http'

Rails.application.load_tasks

namespace :db do
  desc "Loads all NPS parks into the database."
  task :load => :environment do
    uri = URI.parse('https://developer.nps.gov/api/v1/parks?api_key=QKOFMLeGxDBmGtPa9Yqdy0qnYafTpqFmlz1NR92g&limit=700')
    response = Net::HTTP.get_response(uri)
    body = JSON.parse(response.body)
    body["data"].each do |data|
      if data["images"][0]
        image = data["images"][0]["url"]
      end
      Park.find_or_create_by(name: data["fullName"], description: data["description"], state: data["states"].split(",").first, image: image)
    end
  end
end
